### ISSUE TITLE
Reference error in deployment

### ISSUE THREAD

**Issue by Lechuga87** [aws-samples/chimesdk-sip-voicebot#2]
Hi, I have this error when deploying from CloudShell or Cloud9.
The VoiceConnector was created with the ID that the script can't find.
What should I do? 

Received response status [FAILED] from custom resource. Message returned: NotFoundException: Could not find VoiceConnector with Id 'bcgrv8metg74khc4wlokab' at de_NotFoundExceptionRes (/var/task/index.js:26481:25) at de_PutVoiceConnectorLoggingConfigurationCommandError (/var/task/index.js:25026:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /var/task/index.js:6602:24 at async /var/task/index.js:3943:22 at async /var/task/index.js:7854:53 at async /var/task/index.js:1389:27 at async putLogging (/var/task/index.js:57339:5) at async CreateVoiceConnector (/var/task/index.js:57114:5) at async handler (/var/task/index.js:57676:27)

**Comment by jyjohnson** [comment]
Hi @Lechuga87 -- it may be complaining about the logging. First, delete the stack and all resources. Then, set to 'false' the 2 logging statements in lib/chimesdk-sip-voicebot-stack.ts lines 97 & 98. Redeploy and post back the results. Thanks!

**Comment by Lechuga87** [comment]
Hi @jyjohnson -- I have followed instructions and still face same error. Same result with deployments from Cloud9 and CloudShell. 

I think the error may be related to a variable or a reference in the stack template:
Received response status [FAILED] from custom resource. Message returned: NotFoundException: Could not find VoiceConnector with Id 'f8o3gknhyumoxkjfqb0b0d'. 

The same error appears in a different chime-sdk git code: https://github.com/aws-samples/amazon-chime-sdk-take-back-and-transfer

**Comment by schuettc** [comment]
Can you share the logs of the Custom Resource that is failing?  Does the voice connector ID match?

**Comment by Lechuga87** [comment]
I was able to fix the error by deploying in us-east-1 using CloudShell, setting to false logging and adding write permission to all in /aws/ folder.
BTW there is a typo in installation instruction: 4. cdk bookstrap
